name: Build, Test with Sonar and Deploy to AWS
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Solo despliega en push a la rama main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies for get items
        run: |
          cd get_items/
          pip install -r requirements.txt

      - name: Install dependencies for save items
        run: |
          cd save_item/
          pip install -r requirements.txt

      - name: Install dependencies for delete item
        run: |
          cd delete_item/
          pip install -r requirements.txt

      - name: Install dependencies for update item
        run: |
          cd update_car/
          pip install -r requirements.txt

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM application
        run: sam build -t template.yaml

      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name baluchis --capabilities CAPABILITY_IAM --resolve-s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
